export default function StaticBlur() {
  return (
    <div
      className="
        fixed 
        w-screen 
        flex 
        pt-56 
        flex-col 
        items-center 
        place-items-center 
        before:absolute 
        before:h-[300px] 
        before:w-[480px] 
        before:-translate-x-20
        before:translate-y-96
        before:top-80
        before:right-0
        before:rotate-45 
        before:rounded-full 
        before:bg-gradient-conic 
        before:from-blue-400 
        before:to-transparent 
        before:blur-2xl 
        before:opacity-50 
        before:content-[''] 
        after:absolute 
        after:-z-20 
        after:h-[180px] 
        after:w-[260px]
        after:translate-x-48
        after:translate-y-96
        after:top-56
        after:right-24
        after:bg-gradient-conic 
        after:from-sky-600 
        after:via-blue-800 
        after:blur-2xl 
        after:opacity-80 
        after:content-[''] 
        before:dark:rounded-full 
        before:dark:bg-gradient-to-br 
        before:dark:from-transparent
        before:dark:to-blue-400 
        before:dark:opacity-50 
        after:dark:from-sky-600 
        after:dark:via-blue-800 
        after:dark:opacity-80 
        before:lg:h-[360px] 
        z-[-1]
      ">
    </div>
  );
}
